USE XposStore

--QUERY CONSULTA DE VENTAS EN XPOS
SELECT * FROM TXN_RETAIL_LINE ORDER BY CREATED_DATETIME DESC

--QUERY CONSULTA DE VENTAS POR SKU EN XPOS
SELECT * FROM TXN_RETAIL_LINE WHERE ITEM_SKU = '75004699' ORDER BY CREATED_DATETIME DESC


